/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useStore } from "../state";
import { texts } from "../text";

export function CordPlugged(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/cord.glb");
  const deskState = useStore((state) => state.desk);
  return (
    <>
      {deskState.power && (
        <group ref={group} {...props} dispose={null}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.desk_cord_in_plug.geometry}
            material={nodes.desk_cord_in_plug.material}
          />
        </group>
      )}
    </>
  );
}

export function Outlet(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/cord.glb");

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Outlet__0.geometry}
        material={materials["Scene_-_Root"]}
        position={[0.03, 0.24, -1.25]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.02}
      />
    </group>
  );
}

export function CordFloor(props) {
  const {
    powerOnDesk,
    desk: deskState,
    setButton,
    hideButton,
    setText,
  } = useStore();
  const { printText } = props;
  const playSound = useStore((state) => state.playSound);

  const floorPlugClick = () => {
    printText(texts.floorPlug, "floorPlug");
    setButton({
      text: "Plug in cord",
      click: powerOnDesk,
      afterClick: () => {
        setText(["Okay it's plugged in now."]);
        playSound("deskPower");
      },
      hideButton: hideButton,
    });
  };
  const cordFloor = useRef();
  const { nodes, materials } = useGLTF("/cord.glb");

  return (
    <>
      {!deskState.power && (
        <group ref={cordFloor} onClick={floorPlugClick} dispose={null}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.desk_cord_on_floor.geometry}
            material={nodes.desk_cord_on_floor.material}
          />
        </group>
      )}
    </>
  );
}

useGLTF.preload("/cord.glb");
