/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { useStore } from "../state";

type GLTFResult = GLTF & {
  nodes: {
    lower_Disk: THREE.Mesh;
    upper_disk: THREE.Mesh;
  };
  materials: {
    ["Gray.002"]: THREE.MeshStandardMaterial;
    ["Gray.003"]: THREE.MeshStandardMaterial;
  };
};

export default function Discs(props: JSX.IntrinsicElements["group"]) {
  const printer = useStore((state) => state.printer);
  const collectRingOne = useStore((state) => state.collectRingOne);
  const collectRingTwo = useStore((state) => state.collectRingTwo);
  const ringOne = useStore((state) => state.ringOne);
  const ringTwo = useStore((state) => state.ringTwo);
  const setText = useStore((state) => state.setText);
  const hideButton = useStore((state) => state.hideButton);
  const playSound = useStore((state) => state.playSound);
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/discs.glb") as GLTFResult;

  const handleRingOne = (e) => {
    e.stopPropagation();
    hideButton();
    collectRingOne();
    playSound('pickup');
    setText(["I pick up the ring."]);
  };

  const handleRingTwo = (e) => {
    e.stopPropagation();
    hideButton();
    collectRingTwo();
    playSound('pickup');
    setText(["I pick up ANOTHER ring."]);
  };

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-1.34, 0.56, -0.93]} scale={0.1}>
        {printer.printed.includes("ringOne") && !ringOne.collected && (
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.lower_Disk.geometry}
            material={materials["Gray.002"]}
            onClick={(e) => handleRingOne(e)}
          />
        )}
        {printer.printed.includes("ringTwo") && !ringTwo.collected && (
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.upper_disk.geometry}
            material={materials["Gray.003"]}
            onClick={(e) => handleRingTwo(e)}
          />
        )}
      </group>
    </group>
  );
}

useGLTF.preload("/discs.glb");
