/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function NotebookClosed(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/notebookClosed.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials["Material.005"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023_1.geometry}
        material={materials["notebook cover"]}
      />
    </group>
  );
}

useGLTF.preload("/notebookClosed.glb");